export const contractABI = [
  {
    inputs: [
      { internalType: "address", name: "claimer", type: "address" },
      { internalType: "uint256", name: "expirationTime", type: "uint256" },
      { internalType: "bytes32", name: "hashlock", type: "bytes32" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "depositId", type: "bytes32" },
      { internalType: "bytes", name: "secret", type: "bytes" },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "depositId", type: "bytes32" }],
    name: "cancelDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "depositId", type: "bytes32" }],
    name: "getDeposit",
    outputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "address", name: "claimer", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "expirationTime", type: "uint256" },
      { internalType: "bytes32", name: "hashlock", type: "bytes32" },
      { internalType: "bool", name: "claimed", type: "bool" },
      { internalType: "bool", name: "cancelled", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "depositId", type: "bytes32" }],
    name: "isExpired",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "depositId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "depositor", type: "address" },
      { indexed: true, internalType: "address", name: "claimer", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "expirationTime", type: "uint256" },
      { internalType: "bytes32", name: "hashlock", type: "bytes32" },
    ],
    name: "DepositCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "depositId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "claimer", type: "address" },
      { indexed: false, internalType: "bytes", name: "secret", type: "bytes" },
    ],
    name: "DepositClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "depositId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "depositor", type: "address" },
    ],
    name: "DepositCancelled",
    type: "event",
  },
];
